
import React, { useState } from 'react';
import { ProjectPlan, Category } from '../types';
import TaskItem from './TaskItem';
import { ChevronDownIcon, ListBulletIcon, ArrowDownTrayIcon, PrinterIcon } from './icons/Icons';

interface ProjectPlanDisplayProps {
  plan: ProjectPlan;
}

const CategorySection: React.FC<{ category: Category }> = ({ category }) => {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <div className="bg-slate-800/50 border border-slate-700 rounded-xl mb-6 overflow-hidden shadow-lg no-break-inside">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex justify-between items-center p-5 bg-slate-800 hover:bg-slate-700/50 transition-colors duration-200 no-print"
      >
        <h3 className="text-xl font-bold text-slate-100">{category.category}</h3>
        <ChevronDownIcon
          className={`h-6 w-6 text-slate-400 transform transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}
        />
      </button>
      {/* For printing, we want the content always visible and without the button styling */}
      <div className="hidden print:block p-5 bg-slate-100 border-b border-slate-300">
          <h3 className="text-xl font-bold text-slate-900">{category.category}</h3>
      </div>
      
      <div className={`transition-all duration-500 ease-in-out ${isOpen ? 'max-h-[2000px] opacity-100' : 'max-h-0 opacity-0 print:max-h-none print:opacity-100'}`}>
        <div className="p-5 border-t border-slate-700 print:border-slate-300 print:bg-white">
          {category.tasks.map((task, index) => (
            <TaskItem key={`${category.category}-${index}`} task={task} />
          ))}
        </div>
      </div>
    </div>
  );
};

const ProjectPlanDisplay: React.FC<ProjectPlanDisplayProps> = ({ plan }) => {
  const downloadAsMarkdown = () => {
    let content = "# Blockchain Project Action Plan\n\n";
    plan.forEach((cat) => {
      content += `## ${cat.category}\n\n`;
      cat.tasks.forEach((task) => {
        content += `### [ ] ${task.title}\n`;
        content += `${task.description}\n`;
        if (task.technologies && task.technologies.length > 0) {
          content += `**Technologies:** ${task.technologies.join(', ')}\n`;
        }
        content += `\n`;
      });
      content += `---\n\n`;
    });

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'blockchain-project-plan.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const printToPDF = () => {
    window.print();
  };

  return (
    <section className="print:p-0">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4 no-print">
        <div className="flex items-center">
          <ListBulletIcon className="h-6 w-6 text-indigo-400 mr-3" />
          <h2 className="text-3xl font-bold text-slate-100">Your Action Plan</h2>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={downloadAsMarkdown}
            className="flex items-center px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-100 rounded-lg transition-colors border border-slate-600 text-sm font-medium"
            title="Download as Markdown"
          >
            <ArrowDownTrayIcon className="h-4 w-4 mr-2" />
            Export Text
          </button>
          <button
            onClick={printToPDF}
            className="flex items-center px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors text-sm font-medium"
            title="Print or Save as PDF"
          >
            <PrinterIcon className="h-4 w-4 mr-2" />
            Save as PDF
          </button>
        </div>
      </div>

      <div className="hidden print:block mb-8 text-center">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Blockchain Project Action Plan</h1>
        <p className="text-slate-600">Generated by Blockchain Project Planner</p>
        <hr className="mt-4 border-slate-300" />
      </div>

      <div className="print:text-slate-900">
        {plan.map((category, index) => (
          <CategorySection key={index} category={category} />
        ))}
      </div>
    </section>
  );
};

export default ProjectPlanDisplay;
